### ISSUE TITLE
No mouse and keyboard input

### ISSUE THREAD

**Issue by Advait1306** [HsuJv/vnc-rs#9]
I got this tool connected to my vncserver, although the mouse and keyboard inputs aren't being sent to the server. Could there be an issue with my setup or has this functionality not been implemented?

**Comment by HsuJv** [comment]
Hi @Advait1306 ,

This is only a tool that is used to parse VNC protocol. You may need to send an `X11event` to the server manually by calling VncClient.input(xxxx)
(https://docs.rs/vnc-rs/0.5.1/vnc/client/connection/struct.VncClient.html#method.input)

Since my example didn't implement the client input part, maybe you can refer to [my another client implement on wasm](https://github.com/HsuJv/webgateway/blob/main/webvnc/src/lib.rs)

BRs.

**Comment by Advait1306** [comment]
Okay understood, thank you for clearing this out.
